---
title: "U.S. Election Project"
author: "Arthur, Moritz, San Hong"
date: "2024-09-10"
output: html_document
---

# Setup
```{r setup}

# install.packages("here")
# install.packages("tidyverse")
# install.packages("plm")
# install.packages("stargazer")
# install.packages("readxl")
# install.packages("labelled")
# install.packages("sjlabelled")

library(here)
library(tidyverse)
library(plm)
library(stargazer)
library(readxl)
library(labelled)
library(sjlabelled)

### Change directory here. 
### As long as file structure is same as github structure, directory does not need to be changed.
knitr::opts_knit$set(root.dir = here::here())

```


```{r import data}

### Clean environment
rm(list=ls())

### Import data created in dataset-creation.rmd
df <- read_rds("04. Outputs/2024-10-07_electiondataset.rds")

### Legend of variables (variable name x explanation of each variable)
legend <- sjlabelled::get_label(df) %>%
  as.data.frame() %>% 
  rownames_to_column(var = "variable") %>% 
  rename("label" = ".")

### Data without labels (if necessary)
df_nolabel <- labelled::remove_labels(df)

```


```{r data-check}

temp.variable_list <- c("court_action_none_count_VAR", "court_map_drawn_count_VAR", "court_return_leg_count_VAR", "court_challenge_rejected_count_VAR", "judiciary_VAR")
temp.year_expression_list <- list(expr(year_num == 2012), expr(year_num >= 2012), expr(TRUE))

for(year.sel in temp.year_expression_list){
    print(as_label(year.sel))
    
    for(val in temp.variable_list){
    
    df %>% 
      filter(!!year.sel) %>%
      select(paste0(val)) %>% 
      table() %>% 
      print()
    
  }
}

```


# Functions
```{r custom reg function}
### Creating a function to run multiple regressions simultaneously
f.reg.multi <- function(dv.sav = dv, 
                        iv.sav = iv, 
                        dataframe.sav = p.df, 
                        title.sav = "testingasdf", 
                        effect.sav = "time",
                        type.sav = "within", 
                        dv_label.sav = NULL, 
                        cov_label.sav = NULL,
                        star.type = ifelse(knitr::is_latex_output(),"latex", "text"),
                        star.out = NULL) {
  templist <- list()
  
  for (i in 1:length(dv.sav)){
  
    val <- dv.sav[[i]]
    
    formula_str <- paste0(val, "~", iv.sav)
    
    templist[[i]] <- lm(as.formula(paste(formula_str, collapse = " ")),
                        data = dataframe.sav
                        #, effect = effect.sav, 
                        #model = type.sav
                        )
  }
    
  stargazer(templist,
          type = star.type,
          out = star.out,
          report = "vc*sp",
          title = "asdf",
          dep.var.labels = paste0(title.sav),
          dep.var.labels.include = T,
          # column.sep.width = "0pt",
          float = FALSE,
          header = FALSE,
          # no.space = TRUE,
          font.size = "small",
          column.labels = dv_label.sav,
          covariate.labels = cov_label.sav
          ) %>%
    return()
  
}

```


# Analysis Section

* Focus on regression 2 for now

```{r regression 1}

### Creating panel data dataframe
p.df <- df %>% 
  pdata.frame(index = c("idkey", "year")) %>% 
  mutate(democrat_county_vote_perc = democrat_county_vote / county_totalvotes,
         republican_county_vote_perc = republican_county_vote / county_totalvotes,
         poll_perc =  polling_station / laborForce,
         state_party_control = factor(state_party_control, levels = c("Split", "Democratic", "Republican")))

# Using time fixed effects only, as the unbalanced panel data makes it problematic to run county fixed effect in addition
dv <- c("log(county_totalvotes)", "log(democrat_county_vote)", "log(republican_county_vote)")
iv <- "redistrict_count + log(poll_perc) + log(unemploymentRate) + log(vep_turnout_rate) + state_party_control"
dv_label <- c("TOTAL-CountyVotes", "D-CountyVotes", "REP-CountyVotes", "OTH-CountyVotes")
# cov_label <- c("Redistricting attempts per election cycle", "Polling station per pop (Log)", "VEP turnout rate  (Log)", "DEM State Legislature", "REP State Legislature")

f.reg.multi(dv.sav = dv, iv.sav = iv, 
            dv_label.sav = dv_label, 
            title = "Effect of Redistricting on Party Choice in Presidential Elections")

```

```{r regression 2, results = "asis"}

### Creating panel data dataframe
p.df <- df %>% 
  pdata.frame(index = c("idkey", "year")) %>% 
  mutate(democrat_county_vote_perc = democrat_county_vote / county_totalvotes,
         republican_county_vote_perc = republican_county_vote / county_totalvotes,
         poll_perc =  polling_station / laborForce,
         state_party_control = factor(state_party_control, levels = c("Split", "Democratic", "Republican")))

# Using time fixed effects only, as the unbalanced panel data makes it problematic to run county fixed effect in addition

### WITHOUT polling data results
dv <- c("log(democrat_county_vote_perc)", "log(republican_county_vote_perc)")
iv <- "redistrict_count + log(vep_turnout_rate) + log(unemploymentRate) + state_party_control"
dv_label <- c("DEM candidate's % of county votes (log)", "REP candidate's % of county votes (log)")
cov_label <- c("Redistricting attempts per election cycle [state-level]", 
               "Voting-Eligible-Population turnout rate (log) [state-level]", 
               "Unemployment rate  (log) [county-level]", 
               "State legislature control - DEM", 
               "State legislature control - REP")

f.reg.multi(dv.sav = dv, iv.sav = iv, 
            dv_label.sav = dv_label, cov_label.sav = cov_label, 
            title.sav = ""
            # , star.type = "html",
            # star.out = paste0("05. Visualizations/", today(), "-regression-tbl-nopolling.html")
            )

summary(plm(as.formula(paste0(dv, "~", iv)),
                        data = p.df,
                        effect = "time",
                        model = "within"))

### WITH polling data results
dv <- c("log(democrat_county_vote_perc)", "log(republican_county_vote_perc)")
iv <- "redistrict_count + log(polling_station) + log(vep_turnout_rate) + log(unemploymentRate) + state_party_control"
dv_label <- c("DEM candidate's % of county votes (log)", "REP candidate's % of county votes (log)")
cov_label <- c("Redistricting attempts per election cycle [state-level]", 
               "Polling station per county (log)",
               "Voting-Eligible-Population turnout rate (log) [state-level]", 
               "Unemployment rate  (log) [county-level]", 
               "State legislature control - DEM", 
               "State legislature control - REP")

# Title = Effect of Redistricting on Party Choice in Presidential Elections
f.reg.multi(dv.sav = dv, iv.sav = iv, 
            dv_label.sav = dv_label, cov_label.sav = cov_label, 
            title.sav = ""
            # , star.type = "html",
            # star.out = paste0("05. Visualizations/", today(), "-regression-tbl-polling.html")
            )

# Check N & T
summary(plm(as.formula(paste0(dv, "~", iv)),
                        data = p.df,
                        effect = "time",
                        model = "within"))


```

```{r regression - lagged dv}
### Creating a function to run multiple regressions simultaneously
f.reg.single <- function(dv.sav = dv, 
                        iv.sav = iv, 
                        ctrl.sav = ctrl,
                        dataframe.sav = p.df, 
                        title.sav = "testingasdf", 
                        effect.sav = "time",
                        type.sav = "within", 
                        dv_label.sav = NULL, 
                        cov_label.sav = NULL) {
    
    formula_str <- paste0(dv.sav, "~", iv.sav, "+", ctrl.sav)
    
    model <- plm(as.formula(paste(formula_str, collapse = " ")),
                        data = dataframe.sav,
                        effect = effect.sav, 
                        model = type.sav)
    
  stargazer(model,
          type = starout,
          report = "vc*sp",
          dep.var.labels = paste0(title.sav),
          dep.var.labels.include = T,
          column.sep.width = "0pt",
          float = FALSE,
          header = FALSE,
          no.space = TRUE,
          font.size = "small",
          # specific to this project
          column.labels = dv_label.sav,
          covariate.labels = cov_label.sav
          ) %>%
    return()
  
}

# Using time fixed effects only, as the unbalanced panel data makes it problematic to run county fixed effect in addition
dv <- c("log(democrat_county_vote_perc)", "log(republican_county_vote_perc)")
dv <- dv[2]
iv <- "redistrict_count + log(poll_perc) + log(vep_turnout_rate) + state_party_control"
ctrl <- paste0("plm::lag(", dv, ", 4)")
# dv_label <- c("TOTAL-CountyVotes", "D-CountyVotes", "REP-CountyVotes", "OTH-CountyVotes")
# cov_labl <- c("Redistricting count", "No. of polling stations", "Unemployment rate", "VEP turnout rate")

f.reg.single(dv.sav = dv, iv.sav = iv, ctrl.sav = ctrl, title = dv)

```

```{r did}

### Panel Data Frame for DID
p.df <- df %>% 
  filter(avg_DEMvote_perc > 0.0001 & avg_REPvote_perc > 0.0001) %>% 
  mutate(time = case_when(year %in% c("2000", "2004", "2008") ~ 0,
                          year %in% c("2012", "2016", "2020") ~ 1)) %>% 
  mutate(interaction_judiciary = time * judiciary_VAR,
         interaction_court_action_none_count = time * court_action_none_count_VAR,
         interaction_court_map_drawn_count = time * court_map_drawn_count_VAR,
         interaction_court_return_leg_count = time * court_return_leg_count_VAR,
         interaction_court_challenge_rejected_count = time * court_challenge_rejected_count_VAR) %>% 
  pdata.frame(index = c("state_abv", "year")) 


# Data-check for DID
table(p.df$time)
table(p.df$judiciary_VAR)
table(p.df$judiciary_VAR[p.df$time == 1])
table(p.df$judiciary_VAR[p.df$time == 0])
table(p.df$interaction_judiciary)

```

```{r}
### WITH judiciary_VAR
dv <- c("avg_DEMvote_perc", "avg_REPvote_perc", "log(vep_turnout_rate)")
iv <- "judiciary_VAR + time + interaction_judiciary + log(vep_turnout_rate) + log(state_unemploymentRate) + log(gdp_state)"
dv_label <- c("DEM candidate's % of county votes (log)", "REP candidate's % of county votes (log)", "Voting-Eligible-Population turnout rate (log)")
cov_label <- c("Treatment/Control Group (1/0) - Any Judiciary Action Taken", 
               "Time Period After/Before (1/0)",
               "Interaction (Judicial x Time)",
               "Voting-Eligible-Population turnout rate (log)", 
               "Unemployment rate  (log)",
               "GDP (log)"
               #, "State legislature control - DEM", 
               #"State legislature control - REP"
               )

# Title = Effect of Redistricting on Party Choice in Presidential Elections
f.reg.multi(dv.sav = dv, iv.sav = iv, 
            dv_label.sav = dv_label, cov_label.sav = cov_label, 
            title.sav = ""
            , star.type = "html",
            star.out = paste0("05. Visualizations/", today(), "-regression-tbl-polling-did-judicial.html")
            )

# Check N & T
summary(plm(as.formula(paste0(dv, "~", iv)),
                        data = p.df
                        , effect = "twoway",
                        model = "within"
           ))

summary(lm(as.formula(paste0(dv[2], "~", iv)),
                      data = p.df
           ))

```

```{r}
### WITH court_map_drawn_count
dv <- c("avg_DEMvote_perc", "avg_REPvote_perc", "log(vep_turnout_rate)")
iv <- "court_map_drawn_count_VAR + time + interaction_court_map_drawn_count + log(vep_turnout_rate) + log(state_unemploymentRate) + log(gdp_state)"
dv_label <- c("DEM candidate's % of county votes (log)", "REP candidate's % of county votes (log)", "Voting-Eligible-Population turnout rate (log)")
cov_label <- c("Treatment/Control Group (1/0) - Map Drawn by Court", 
               "Time Period After/Before (1/0)",
               "Interaction (Judicial x Time)",
               "Voting-Eligible-Population turnout rate (log)", 
               "Unemployment rate  (log)",
               "GDP (log)"
               #, "State legislature control - DEM", 
               #"State legislature control - REP"
               )

# Title = Effect of Redistricting on Party Choice in Presidential Elections
f.reg.multi(dv.sav = dv, iv.sav = iv, 
            dv_label.sav = dv_label, cov_label.sav = cov_label, 
            title.sav = ""
            , star.type = "html",
            star.out = paste0("05. Visualizations/", today(), "-regression-tbl-polling-did-court-draw.html")
            )

# Check N & T
summary(plm(as.formula(paste0(dv, "~", iv)),
                        data = p.df
                        , effect = "twoway",
                        model = "within"
           ))
```

```{r}
### WITH court_return_leg_count
dv <- c("avg_DEMvote_perc", "avg_REPvote_perc", "log(vep_turnout_rate)")
iv <- "court_return_leg_count_VAR + time + interaction_court_return_leg_count + log(vep_turnout_rate) + log(state_unemploymentRate) + log(gdp_state)"
dv_label <- c("DEM candidate's % of county votes (log)", "REP candidate's % of county votes (log)", "Voting-Eligible-Population turnout rate (log)")
cov_label <- c("Treatment/Control Group (1/0) - Map Drawn by Court", 
               "Time Period After/Before (1/0)",
               "Interaction (Judicial x Time)",
               "Voting-Eligible-Population turnout rate (log)", 
               "Unemployment rate  (log)",
               "GDP (log)"
               #, "State legislature control - DEM", 
               #"State legislature control - REP"
               )

# Title = Effect of Redistricting on Party Choice in Presidential Elections
f.reg.multi(dv.sav = dv, iv.sav = iv, 
            dv_label.sav = dv_label, cov_label.sav = cov_label, 
            title.sav = ""
            , star.type = "html",
            star.out = paste0("05. Visualizations/", today(), "-regression-tbl-polling-did-court-return-leg.html")
            )

# Check N & T
summary(plm(as.formula(paste0(dv, "~", iv)),
                        data = p.df
                        , effect = "twoway",
                        model = "within"
           ))
```

```{r}
### WITH court_challenge_rejected_count
dv <- c("avg_DEMvote_perc", "avg_REPvote_perc", "log(vep_turnout_rate)")
iv <- "court_challenge_rejected_count_VAR + time + interaction_court_challenge_rejected_count + log(vep_turnout_rate) + log(state_unemploymentRate) + log(gdp_state)"
dv_label <- c("DEM candidate's % of county votes (log)", "REP candidate's % of county votes (log)", "Voting-Eligible-Population turnout rate (log)")
cov_label <- c("Treatment/Control Group (1/0) - Map Drawn by Court", 
               "Time Period After/Before (1/0)",
               "Interaction (Judicial x Time)",
               "Voting-Eligible-Population turnout rate (log)", 
               "Unemployment rate  (log)",
               "GDP (log)"
               #, "State legislature control - DEM", 
               #"State legislature control - REP"
               )

# Title = Effect of Redistricting on Party Choice in Presidential Elections
f.reg.multi(dv.sav = dv, iv.sav = iv, 
            dv_label.sav = dv_label, cov_label.sav = cov_label, 
            title.sav = ""
            , star.type = "html",
            star.out = paste0("05. Visualizations/", today(), "-regression-tbl-polling-did-court-reject.html")
            )

# Check N & T
summary(plm(as.formula(paste0(dv, "~", iv)),
                        data = p.df
                        , effect = "twoway",
                        model = "within"
           ))

```
