---
title: "U.S. Election Project"
author: "Arthur, Moritz, San Hong"
date: "2024-09-24"
output: html_document
---

```{r setup, include = TRUE}

library(here)
library(tidyverse)
library(stringi)

### Change directory here. 
### As long as file structure is same as github structure, directory does not need to be changed.
knitr::opts_knit$set(root.dir = here::here())

```

# Preparing Data for Merge
```{r df_turnout}

### Clean workspace
rm(list=ls())

### Import voter turnout data
### https://election.lab.ufl.edu/dataset/1980-2022-general-election-turnout-rates/ 
df_turnout <- read_csv("02. Inputs/Turnout_1980_2022_v1.0.csv")

### Preparing dataframe for merging
df1 <- df_turnout %>% 
  # Changing percent string to numeric
  mutate(across(c(NONCITIZEN_PCT, VEP_TURNOUT_RATE, VAP_TURNOUT_RATE), ~as.numeric(sub("%", "", .)))) %>%
  # Removing columns unrelated to voter turnout rate
  select(1:3, VEP_TURNOUT_RATE, VAP_TURNOUT_RATE, VEP, VAP) %>% 
  # Renaming column names to lowercase (for easier merge)
  rename_all(tolower)

```

```{r df_candivote}

### Import "votes for each presidential candidate"
### https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/VOQCHQ
df_candivote <- read_csv("02. Inputs/countypres_2000-2020.csv")

### Preparing dataframe for merging
df2_1 <- df_candivote %>% 
  # Only considering Democrat, Republican, and Other (ignoring Green, Libertarian, etc)
  mutate(party_n = case_when(party == "DEMOCRAT" ~ "Democrat",
                             party == "REPUBLICAN" ~ "Republican",
                             TRUE ~ "Other")) %>% 
  group_by(year, state, county_name, office, party_n) %>% 
  summarize(county_partyvotes = sum(candidatevotes),
            .groups = "drop") %>% 
  # Changing state and county names from all caps to sentence caps
  mutate_at(c("state", "county_name"), ~str_to_sentence(.)) %>% 
  # Redundancy check, narrowing to only U.S. Presidential elections
  filter(office == "US PRESIDENT") %>% 
  select(-office) %>% 
  # Find county level total votes
  group_by(year, state, county_name) %>% 
  mutate(county_totalvotes = sum(county_partyvotes)) %>% 
  # Pivot to wide data format
  mutate(party = paste0(party_n,"_county_vote")) %>% 
  select(-party_n) %>% 
  pivot_wider(names_from = party,
              values_from = county_partyvotes) %>% 
  # Reorder variables
  relocate(Republican_county_vote, .after = Democrat_county_vote) %>% 
  relocate(county_totalvotes, .after = Other_county_vote) %>% 
  # Renaming column names to lowercase (for easier merge)
  rename_all(tolower) %>% 
  # Getting state level totals
  group_by(year, state) %>% 
  mutate(state_totalvotes = sum(county_totalvotes))

# Extracting state abbreviations
df2_2 <- df_candivote %>% 
  select(state, state_po) %>% 
  mutate(state = str_to_sentence(state)) %>% 
  rename(state_abv = state_po) %>% 
  group_by(state) %>% 
  unique()

### Merging back state abbreviations
df2 <- left_join(df2_1, df2_2, by = "state") %>% 
  relocate(state_abv, .after = state)

```

```{r df_crime}

### Import state crime rate
### https://corgis-edu.github.io/corgis/csv/state_crime/
df_crime <- read_csv("02. Inputs/state_crime.csv")

### Preparing dataframe for merging
df3 <- df_crime %>% 
  # Renaming column names to lowercase (for easier merge)
  rename_all(tolower) %>% 
  # Renaming column names to "crime" for easier indexing
  rename_with(~ gsub("data","statecrime",.), contains("data")) %>% 
  # Merging state abbreviations
  mutate(state = str_to_sentence(state)) %>% 
  left_join(df2_2, by = "state") %>% 
  relocate(state_abv, .after = state)

```

```{r df_redist}

### Import redistricting data
### https://redistricting.lls.edu/national-overview/?colorby=Plan%20Status&level=Congress&cycle=2020
df_redist <- read_csv("02. Inputs/StatesAndCyclesData_production-20240301a.csv")

df4_1 <- df_redist %>% 
  # Renaming column names to lowercase (for easier merge)
  rename_all(tolower) %>% 
  # Extracting the year the redistricting plan was passed
  mutate(pass_year = as.numeric(substr(passed, start = 1, stop = 4))) %>% 
  # Dropping entries without such information
  drop_na(pass_year) %>% 
  # New year variable based on election cycle
  mutate(elect_year = case_when(
    (pass_year > 1996 & pass_year <= 2000) ~ 2000,
    (pass_year > 2000 & pass_year <= 2004) ~ 2004,
    (pass_year > 2004 & pass_year <= 2008) ~ 2008,
    (pass_year > 2008 & pass_year <= 2012) ~ 2012,
    (pass_year > 2012 & pass_year <= 2016) ~ 2016,
    (pass_year > 2016 & pass_year <= 2020) ~ 2020,
    (pass_year > 2020 & pass_year <= 2024) ~ 2024
  )) %>% 
  # Filters that need to be adjusted
  filter(level == "State Lower") %>%
  select(state, pass_year, elect_year, level, `party control`, `drawn by`)

df4_2 <- df4_1 %>% 
  group_by(elect_year, state) %>%
  summarize(n = n(),
            rep_ctrl = sum(`party control` == "Republican"),
            dem_ctrl = sum(`party control` == "Democratic"),
            split_ctrl = sum(`party control` == "Split")) %>%
  mutate(state_party_control = case_when(!rep_ctrl + dem_ctrl + split_ctrl == n ~ "Uncertain",
                           rep_ctrl / n > 0.5 ~ "Republican",
                           dem_ctrl / n > 0.5 ~ "Democratic",
                           split_ctrl / n > 0.5 ~ "Split",
                           TRUE ~ "Split")) %>% 
  select(-rep_ctrl, -dem_ctrl, -split_ctrl) %>% 
  arrange(desc(n)) %>% 
  rename(redistrict_count = n)

```

```{r df_unemp, results='hide', message=FALSE}
### Source county unemployment rate from the following link:
### https://www.bls.gov/lau/tables.htm#cntyaa

### Row binding all annual county unemployment data from 1997 to 2003

# # Collate files' paths
# unemp_county_files <- list.files(path = "02. Inputs/county_unemployment", full.names = TRUE, recursive = TRUE)
# 
# # Prepare empty data frame to catch
# df_unemp <- data.frame(matrix(ncol = 8, nrow = 0))
# 
# # Loop each file into binding
# for (file in unemp_county_files) {
#   # Read xslx file
#   file_data <- read_xlsx(file)
#   # Remove headers and unnecessary columns to match to empty data frame
#   file_slice <- file_data[-c(1:5),-c(1,6)] %>% 
#     # Remove NA (Note: there are data entry of "N.A." in character)
#     na.omit()
#   # Rename columns
#   names(file_slice) <- c("state_code",
#                          "county_code",
#                          "countyName_StateAbbreviation",
#                          "year",
#                          "laborForce",
#                          "employed",
#                          "unemployed",
#                          "unemploymentRate")
#   # Rbind
#   df_unemp <- rbind(df_unemp, file_slice)
# }
# 
# # Save df_unemp as an intermediary file
# saveRDS(df_unemp, file = paste0("03. Intermediaries/df_unemp.rds"))

# Reimport df_unemp
df_unemp <- read_rds("03. Intermediaries/df_unemp.rds")

### Preparing data frame for merge
# County expressions that need to be excluded
countyexpressions <- c(" Borough/municipality" = "",  " Borough/city" = "", " County/city" = "", " County" = "", " Census Area"  = "", " Borough" = "", "/" = "")

df5 <- df_unemp %>% 
  # Extracting state abbreviations
  mutate(state_abv = case_when(
    # District of Columbia manually labelled as "DC"
    countyName_StateAbbreviation == "District of Columbia" ~ "DC",
    # Extracting the abbreviation from the last two letters of the countyName_StateAbbreviation string
    TRUE ~ substr(countyName_StateAbbreviation, start = nchar(countyName_StateAbbreviation)-1, stop = nchar(countyName_StateAbbreviation)))) %>% 
  # Extracting county name
  mutate(county_name.temp1 = str_remove_all(countyName_StateAbbreviation, paste0(", ", state_abv)),
         # Harmonizing county name by removing expressions in `countryexpressions`
         county_name.temp2 = str_remove_all(county_name.temp1, countyexpressions),
         # Harmonizing county names by changing to sentence case
         county_name = str_to_sentence(county_name.temp2)) %>%
  # Selecting relevant columns only
  select(year, state_abv, county_name, laborForce, employed, unemployed, unemploymentRate) %>% 
  # Change NA string to null values
  mutate_all(~na_if(., "N.A.")) %>% 
  # Changing variable to numeric
  mutate(across(c("year", "laborForce", "employed", "unemployed", "unemploymentRate"
                  ), ~as.numeric(.)))

```

```{r df_poll}
### Source Polling Station Data from the following linK:
### https://github.com/PublicI/us-polling-places/tree/update-2020

### Row bind all the county-level polling station data

# # Collate all files path
# poll_files_all <- list.files(path = "02. Inputs/us-polling-places/data", full.names = TRUE, recursive = TRUE)
# 
# # Filter for only polling station data
# poll_files <- c()
# for (file in poll_files_all){
#   if(grepl("/output/", file)){
#     poll_files <- append(poll_files, file)
#   }
# }
# 
# df_poll <- data.frame(matrix(ncol = 15, nrow = 0))
# 
# # Loop each file into binding
# for (file in poll_files) {
#   # Read csv file
#   file_data <- read.csv(file)
#   # Append state name from file path
#   # state <- unlist(strsplit(file, "/"))[4]
#   # file_data$state <- str_to_sentence(state)
#   # Safety check for same number of columns before binding
#   if (ncol(file_data) == 15){
#     # Rbind
#     df_poll <- rbind(df_poll, file_data)
#   }
#   else{
#     print(file)
#     print(ncol(file_data))
#   }
# }
# 
# # Save df_poll as an intermediary file
# saveRDS(df_poll, file = paste0("03. Intermediaries/df_poll.rds"))

# Reimport df_poll
df_poll <- read_rds("03. Intermediaries/df_poll.rds")

### Prepare data frame for merge
df6 <- df_poll %>% 
  # replace county name with "non-county" value when county name is NA or empty
  mutate(county_name = if_else((county_name == "" | is.na(county_name)), "non-county", county_name)) %>%
  # Harmonise cases
  mutate(county_name = str_to_sentence(county_name)) %>% 
  # Extract election year & harmonize to numeric
  mutate(election_year = as.numeric(substr(election_date, start = 1, stop = 4))) %>% 
  # filter out jurisdiction with no names (they are likely precincts)
  filter(jurisdiction != "") %>%
  # Tally by election year for each county
  group_by(election_year, county_name, state) %>% 
  summarize(polling_station = n())

```

# Merging Data
```{r merge}

### Merge dataframes
# Df2 is primary, because it has county level and state level
df_merge1 <- df2 %>% 
  left_join(df1 %>%  select(-state), by = join_by("year" == "year", "state_abv" == "state_abv")) %>%  
  left_join(df3 %>% select(-state), by = join_by("year" == "year", "state_abv" == "state_abv")) %>% 
  left_join(df4_2, by = join_by("year" == "elect_year", "state_abv" == "state")) %>% 
  mutate(idkey = paste0(state_abv,"_", county_name)) %>%
  relocate(idkey, .before = 1)

df_merge2 <- df_merge1 %>% 
  left_join(df5, by = join_by("year" == "year", "state_abv" == "state_abv", "county_name" == "county_name")) %>%
  left_join(df6, by = join_by("year" == "election_year", "county_name" == "county_name", "state_abv" == "state" )) %>% 
  mutate(across(c("state_abv", "county_name", "state_party_control"), ~as.factor(.)))

df_final <- df_merge2

```

```{r export}
### Save dataset
# write.csv(df_final, file = paste0("04. Outputs/", today(), "_electiondataset.csv"))
saveRDS(df_final, file = paste0("04. Outputs/", today(), "_electiondataset.rds"))

```

# Additional Data Edits
```{r additional edits}

df <- read_rds("04. Outputs/2024-09-26_electiondataset.rds")

```

