---
title: "U.S. Election Project"
author: "Arthur, Moritz, San Hong"
date: "2024-09-24"
output: html_document
---

```{r setup, include = TRUE}

# install.packages("usa")

library(here)
library(tidyverse)
library(stringi)
library(usa)
library(expss)
library(tidycensus)

### Change directory here. 
### As long as file structure is same as github structure, directory does not need to be changed.
knitr::opts_knit$set(root.dir = here::here())

```

# Create a Base Dataframe
```{r base_df}

### Function to create a base dataframe
f.create.basedf <- function(df, start_year, end_year){
  electionyears <- c() # Empty dataframe to collect election years vector
  temp.list <- list() # Empty list to nest year-added dataframes into
  for(val in start_year:end_year){
    # Narrow down election years (years that are divisible by 4)
    if(val %% 4 == 0) {
      electionyears <- c(electionyears, val)
    }
  }
  # Create year-added dataframes with U.S. state data
  for(i in 1:length(electionyears)){
    val <- electionyears[[i]]
    temp.df <- df %>% 
      mutate(year = val) %>% 
      relocate(year, .before = 1)
    # Save data into a nested list
    temp.list[[i]] <- temp.df
  }
  # Bind the rows of the nested list into the final base dataframe
  return(bind_rows(temp.list))
}

base_df <- f.create.basedf(usa::states, 2000, 2020) %>% 
  rename(state_name = name,
         state_abv = abb)
  
```

```{r base_redist_df}

### Import redistricting data
### https://redistricting.lls.edu/national-overview/?colorby=Plan%20Status&level=Congress&cycle=2020
IMPORT.redist <- read_csv("02. Inputs/StatesAndCyclesData_production-20240301a.csv")

### Preparing dataframe for merging
df_redist.temp1 <- IMPORT.redist %>% 
  # Renaming column names to lowercase (for easier merge)
  rename_all(tolower) %>% 
  # Extracting the year the redistricting plan was passed
  mutate(pass_year = as.numeric(substr(passed, start = 1, stop = 4))) %>% 
  # Dropping entries without such information
  drop_na(pass_year) %>% 
  # New year variable based on election cycle
  mutate(elect_year = case_when(
    (pass_year > 1996 & pass_year <= 2000) ~ 2000,
    (pass_year > 2000 & pass_year <= 2004) ~ 2004,
    (pass_year > 2004 & pass_year <= 2008) ~ 2008,
    (pass_year > 2008 & pass_year <= 2012) ~ 2012,
    (pass_year > 2012 & pass_year <= 2016) ~ 2016,
    (pass_year > 2016 & pass_year <= 2020) ~ 2020,
    (pass_year > 2020 & pass_year <= 2024) ~ 2024
  )) %>% 
  # Filter to congressional redistricting
  filter(level == "Congress") %>%
  select(state, elect_year, `court action`)

# Editing data for redistricting & court actions
df_redist.temp2 <- df_redist.temp1 %>% 
  # Add a "no redistricting" variable
  mutate(`court action` = if_else(is.na(`court action`), "court_action_none", `court action`)) %>%
  # Lower case entries for harmonization
  mutate(`court action` = tolower(`court action`)) %>%
  # Count the number of instances per court action category
  group_by(state, elect_year, `court action`) %>% 
  summarize(n = n(), .groups = "drop") %>%
  # Change to wider dataframe
  pivot_wider(names_from = `court action`,
              values_from = n)

# Check if all-NAs exist
df_redist.temp2 %>%
  filter(is.na(`court_action_none`) & is.na(`rejected challenge to leg. map`) 
         & is.na(`court drew map (not legislature)`) & is.na(`court sent map back to legislature`)
         & is.na(`pending litigation`) & is.na(`rejected challenge to commission map`)) %>%
  str()

# Consolidate court actions
df_redist.temp3 <- df_redist.temp2 %>% 
  replace(is.na(.), 0) %>% 
  mutate(court_challenge_rejected = `rejected challenge to leg. map` + `rejected challenge to commission map`) %>%
  select(-`rejected challenge to leg. map`, -`rejected challenge to commission map`, -`pending litigation`) %>% 
  rename(court_map_drawn_count = `court drew map (not legislature)`,
         court_return_leg_count = `court sent map back to legislature`,
         court_action_none_count = court_action_none,
         court_challenge_rejected_count = court_challenge_rejected
         )

### Merge redistricting data with 
base_redist_df <- left_join(base_df, df_redist.temp3,
          by = join_by("year" == "elect_year", "state_abv" == "state")) %>% 
  mutate(across(starts_with("court_"), ~ coalesce(as.numeric(.), 0))) %>% 
  mutate(redistrict_VAR = case_when(court_action_none_count > 0 | court_map_drawn_count > 0 | court_return_leg_count > 0 | court_challenge_rejected_count > 0 ~ 1,
                                   TRUE ~ 0)) %>% 
  relocate(redistrict_VAR, .before = court_action_none_count)

### Cleanwork space
rm(list = grep("temp", ls(), value = TRUE))

```

# Preparing Data for Merge

```{r df_housevote}

### Import house votes
### https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/IG0UN2 
IMPORT.housevote <- read_csv("02. Inputs/1976-2022-house.csv")

### Preparing dataframe for merging
df_housevote.temp1 <- IMPORT.housevote %>%
  # Only considering Democrat, Republican candidates. Other parties are classified as "OTHER".
  mutate(party2 = case_when(party == "DEMOCRAT" ~ "DEM",
                            party == "REPUBLICAN" ~ "REP",
                            TRUE ~ "OTHER")) %>% 
  group_by(year, state_po, district, party2) %>% 
  summarize(party_vote = sum(candidatevotes),
            .groups = "drop") %>% 
  # Creating wide dataframe
  pivot_wider(id_cols = 1:3,
              names_from = party2,
              values_from = party_vote) %>% 
  # Merging back total votes per district
  left_join(IMPORT.housevote %>% select(year, state_po, district, totalvotes) %>% distinct(),
            by = join_by("year" == "year", "state_po" == "state_po", "district" == "district")) %>% 
  # Replacing missing values with 0 (missing values caused by the pivot_wider)
  replace(is.na(.), 0) %>% 
  # Relocating columns to more appropriate locations
  relocate(totalvotes, .after = district) %>% 
  relocate(OTHER, .after = REP) %>% 
  # Filtering states with total votes <= 1 (which indicate no contestation or NA values)
  filter(totalvotes >= 1) %>% 
  # Converting votes per party into percentage of votes cast per district
  mutate(across(c("DEM", "REP", "OTHER"), ~ ./totalvotes , .names = '{col}_perc'))

# Identifying average percentage of votes cast for a party in a state (average across districts)
df_housevote.temp2 <- df_housevote.temp1 %>% 
  group_by(year, state_po) %>% 
  summarize(avg_DEMvote_perc = mean(DEM_perc, na.rm = T),
            avg_REPvote_perc = mean(REP_perc, na.rm = T),
            avg_OTHERvote_perc = mean(OTHER_perc, na.rm = T),
            state_totalvotes = sum(totalvotes, na.rm = T))

# Create variable for ex ante/lagged closeness of votes (taking the difference of vote counts between top 1 and top 2 candidate) ~ smaller gap = closer race
df_housevote <- df_housevote.temp2 %>% 
  mutate(first = pmax(avg_DEMvote_perc, avg_REPvote_perc, avg_OTHERvote_perc),
         runner = 1 - pmax(avg_DEMvote_perc, avg_REPvote_perc, avg_OTHERvote_perc) - pmin(avg_DEMvote_perc, avg_REPvote_perc, avg_OTHERvote_perc),
         vote_closeness = first - runner) %>% 
  select(-first, -runner) %>% 
  # introduce lag
  ungroup() %>% 
  filter(state_po != "DC") %>% 
  group_by(state_po) %>% 
  mutate(lagged_vote_closeness = c(rep(NA, 2), head(vote_closeness, -2)))

### Cleanwork space
rm(list = grep("temp", ls(), value = TRUE))

```


```{r df_turnout}

### Import voter turnout data
### https://election.lab.ufl.edu/dataset/1980-2022-general-election-turnout-rates/ 
IMPORT.turnout <- read_csv("02. Inputs/Turnout_1980_2022_v1.0.csv")

### Preparing dataframe for merging
df_turnout <- IMPORT.turnout %>% 
  # Changing percent string to numeric
  mutate(across(c(NONCITIZEN_PCT, VEP_TURNOUT_RATE, VAP_TURNOUT_RATE), ~as.numeric(sub("%", "", .)))) %>%
  # Removing columns unrelated to voter turnout rate
  select(1:3, VEP_TURNOUT_RATE, VAP_TURNOUT_RATE, VEP, VAP) %>% 
  # Renaming column names to lowercase (for easier merge)
  rename_all(tolower) %>% 
  # Add lagged variable
  mutate(lagged_vep = c(vep_turnout_rate[(3:length(vep_turnout_rate))], NA, NA), .by = state_abv)

```

```{r df_crime}

# ### Import state crime rate
# ### https://corgis-edu.github.io/corgis/csv/state_crime/
# IMPORT.crime <- read_csv("02. Inputs/state_crime.csv")
# 
# ### Preparing dataframe for merging
# df_crime <- IMPORT.crime %>% 
#   # Renaming column names to lowercase (for easier merge)
#   rename_all(tolower) %>% 
#   # Renaming column names to "crime" for easier indexing
#   rename_with(~ gsub("data","statecrime",.), contains("data"))
# 
# # Extract statenames from df_crime and df_base to check if names are identical
# df_crime_statename.temp <- df_crime %>% select(state) %>% distinct() %>% arrange() %>% mutate(x = 1)
# df_base_statename.temp <- base_df %>% select(state_name) %>% distinct() %>% arrange() %>% mutate(y = 1)
# full_join(df_crime_statename.temp, df_base_statename.temp, by = join_by("state" == "state_name")) %>% 
#   filter(is.na(x) | is.na(y))
# 
# ### Cleanwork space
# rm(list = grep("temp", ls(), value = TRUE))

```

```{r df_fbi_crime}

### Source violent offenses reported by state:
### https://cde.ucr.cjis.gov/LATEST/webapp/#/pages/explorer/crime/crime-trend

### Row binding all annual county unemployment data from 1997 to 2003

# Collate files' paths
# fbi_crime_files.temp1 <- list.files(path = "02. Inputs/violent crimes FBI", full.names = TRUE, recursive = TRUE)
# 
# # Prepare empty data frame to catch
# df_fbi_crime.temp1 <- data.frame(matrix(ncol = 253, nrow = 0))
# 
# # Loop each file into fbi_crime_files.temp1
# for (file in fbi_crime_files.temp1) {
#   # Read xslx file
#   file_data <- read_csv(file)
#   # Rbind
#   df_fbi_crime.temp1 <- rbind(df_fbi_crime.temp1, file_data)
# }
# 
# # Save df_fbi_crime.temp1 as an intermediary file
# saveRDS(df_fbi_crime.temp1, file = paste0("03. Intermediaries/df_fbi_crime.rds"))

# Reimport df_poll
df_fbi_crime.temp1 <- read_rds("03. Intermediaries/df_fbi_crime.rds")

### 
df_fbi_crime <- df_fbi_crime.temp1 %>% 
  filter(!grepl("Clearances", series)) %>% 
  rename(state = series) %>% 
  pivot_longer(cols = !1,
               names_to = "date",
               values_to = "violent_crime_month") %>% 
  mutate(year = as.numeric(str_sub(date, start = -4, end = -1))) %>% 
  relocate(year, .after = state) %>% 
  group_by(year, state) %>% 
  summarize(violent_crime = sum(violent_crime_month), .groups = "drop")

```

```{r df_unemp, results='hide', message=FALSE}
### Source county unemployment rate from the following link:
### https://www.bls.gov/lau/tables.htm#cntyaa

### Row binding all annual county unemployment data from 1997 to 2003

# Collate files' paths
# unemp_county_files <- list.files(path = "02. Inputs/county_unemployment", full.names = TRUE, recursive = TRUE)
# 
# # Prepare empty data frame to catch
# df_unemp <- data.frame(matrix(ncol = 8, nrow = 0))
# 
# # Loop each file into binding
# for (file in unemp_county_files) {
#   # Read xslx file
#   file_data <- read_xlsx(file)
#   # Remove headers and unnecessary columns to match to empty data frame
#   file_slice <- file_data[-c(1:5),-c(1,6)] %>%
#     # Remove NA (Note: there are data entry of "N.A." in character)
#     na.omit()
#   # Rename columns
#   names(file_slice) <- c("state_code",
#                          "county_code",
#                          "countyName_StateAbbreviation",
#                          "year",
#                          "laborForce",
#                          "employed",
#                          "unemployed",
#                          "unemploymentRate")
#   # Rbind
#   df_unemp <- rbind(df_unemp, file_slice)
# }
# 
# # Save df_unemp as an intermediary file
# saveRDS(df_unemp, file = paste0("03. Intermediaries/df_unemp.rds"))

# Reimport df_unemp
df_unemp <- read_rds("03. Intermediaries/df_unemp.rds")

### Preparing data frame for merge
df_unemp_state.temp1 <- df_unemp %>% 
  # Extracting state abbreviations
  mutate(state_abv = case_when(
    # District of Columbia manually labelled as "DC"
    countyName_StateAbbreviation == "District of Columbia" ~ "DC",
    # Extracting the abbreviation from the last two letters of the countyName_StateAbbreviation string
    TRUE ~ substr(countyName_StateAbbreviation, start = nchar(countyName_StateAbbreviation)-1, stop = nchar(countyName_StateAbbreviation)))) %>% 
  # Selecting relevant columns only
  select(year, state_abv, laborForce, employed, unemployed, unemploymentRate) %>% 
  # Change NA string to null values
  mutate_all(~na_if(., "N.A.")) %>% 
  # Changing variable to numeric
  mutate(across(c("year", "laborForce", "employed", "unemployed", "unemploymentRate"
                  ), ~as.numeric(.)))

# State aggregated data
df_unemp_state.temp2 <- df_unemp_state.temp1 %>% 
  group_by(year, state_abv) %>% 
  summarize(state_laborForce = sum(laborForce, na.rm = T),
            state_employed = sum(employed, na.rm = T),
            state_unemployed = sum(unemployed, na.rm = T),
            state_unemploymentRate = mean(unemploymentRate, na.rm = T))

df_unemp_state <- df_unemp_state.temp2

### Cleanwork space
rm(list = grep("temp", ls(), value = TRUE))

```

```{r df_poll}
### Source Polling Station Data from the following linK:
### https://github.com/PublicI/us-polling-places/tree/update-2020

### Row bind all the county-level polling station data

# # Collate all files path
# poll_files_all <- list.files(path = "02. Inputs/us-polling-places/data", full.names = TRUE, recursive = TRUE)
# 
# # Filter for only polling station data
# poll_files <- c()
# for (file in poll_files_all){
#   if(grepl("/output/", file)){
#     poll_files <- append(poll_files, file)
#   }
# }
# 
# df_poll <- data.frame(matrix(ncol = 15, nrow = 0))
# 
# # Loop each file into binding
# for (file in poll_files) {
#   # Read csv file
#   file_data <- read.csv(file)
#   # Append state name from file path
#   # state <- unlist(strsplit(file, "/"))[4]
#   # file_data$state <- str_to_sentence(state)
#   # Safety check for same number of columns before binding
#   if (ncol(file_data) == 15){
#     # Rbind
#     df_poll <- rbind(df_poll, file_data)
#   }
#   else{
#     print(file)
#     print(ncol(file_data))
#   }
# }
# 
# # Save df_poll as an intermediary file
# saveRDS(df_poll, file = paste0("03. Intermediaries/df_poll.rds"))

# Reimport df_poll
df_poll <- read_rds("03. Intermediaries/df_poll.rds")

### Prepare data frame for merge
df_poll_state <- df_poll %>% 
  # replace county name with "non-county" value when county name is NA or empty
  mutate(county_name = if_else((county_name == "" | is.na(county_name)), "non-county", county_name)) %>%
  # Harmonise cases
  mutate(county_name = str_to_sentence(county_name)) %>% 
  # Extract election year & harmonize to numeric
  mutate(election_year = as.numeric(substr(election_date, start = 1, stop = 4))) %>% 
  # filter out jurisdiction with no names (they are likely precincts)
  # filter(jurisdiction != "") %>%
  # Tally by election year for each state
  group_by(election_year, state) %>% 
  summarize(polling_station = n())

```

```{r df_gdp}

### Import state GDP
### https://www.bea.gov/data/gdp/gdp-state 
IMPORT.gdp <- read_csv("02. Inputs/SAGDP1__ALL_AREAS_1997_2023.csv")

### Preparing dataframe for merging
df_gdp <- IMPORT.gdp %>% 
  select(-`2021`, -`2022`, -`2023`) %>% 
  # Harmonize FIPS code
  mutate(GeoFIPS = substr(GeoFIPS, start = 1, stop = 2)) %>%
  # Extract only Real GDP
  filter(LineCode == 1) %>% 
  select(GeoFIPS, `1997`:`2020`) %>% 
  pivot_longer(cols = !1,
               names_to = "year",
               values_to = "gdp_state") %>% 
  mutate(year = as.numeric(year))

### Cleanwork space
rm(list = grep("temp", ls(), value = TRUE))

```

```{r df_wealth_inequality}

### Import state-level wealth inequality 
### https://www.openicpsr.org/openicpsr/project/192306/version/V4/view?path=/openicpsr/192306/fcr:versions/V4&type=project
IMPORT.wealth_ineq <- read_csv("02. Inputs/wealth inequality/state_wealth_inequality.csv")

### Preparing dataframe for merging
df_wealth_inequality <- IMPORT.wealth_ineq %>%
  mutate(state = str_to_sentence(state)) %>% 
  mutate(state = case_when(state == "District of columbia" ~ "District of Columbia",
                           TRUE ~ state)) %>% 
  select(year, state, wealth_gini, income_mean)

```

```{r df_stateparty}

### Import state partisan composition (state controlled by which party?)
### https://github.com/psthomas/state-partisan-composition
### (originally from https://www.ncsl.org/research/about-state-legislatures/partisan-composition.aspx)
IMPORT.stateparty <- read_csv("02. Inputs/state_partisan_composition_1934_2021.csv")

### Preparing dataframe for merging
df_stateparty <- IMPORT.stateparty %>%
  # Filter out any NA values (that are not represented as NA)
  filter(!house_total == 0) %>% 
  filter(!senate_total == 0) %>% 
  # Identify which party has control over state senate
  mutate(senate_party = case_when(senate_dem/senate_total >= 0.5 ~ "DEM",
                                  senate_rep/senate_total >= 0.5 ~ "REP",
                                  is.na(senate_total) | is.na(senate_dem) | is.na(senate_rep) ~ NA,
                                  TRUE ~ "SPLIT")) %>%
  relocate(senate_party, .before = senate_total) %>%
  # Identify which party has control over state house of representatives
  mutate(house_party = case_when(house_dem/house_total >= 0.5 ~ "DEM",
                                  house_rep/house_total >= 0.5 ~ "REP",
                                  is.na(house_total) | is.na(house_dem) | is.na(house_rep) ~ NA,
                                  TRUE ~ "SPLIT")) %>%
  relocate(house_party, .before = house_total) %>%
  # Identify state legislative control - do they control both senate and house?)
  mutate(stateparty_control = case_when(house_party == senate_party ~ house_party,
                                        !house_party == senate_party ~ "SPLIT",
                                        is.na(house_party) | is.na(senate_party) ~ NA,
                                        TRUE ~ NA)) %>%
  select(year, state, stateparty_control) %>% 
  # Change to factor
  mutate(stateparty_control = as.factor(stateparty_control))

```


# Merging Data
Things to join:
* df_housevote
* df_turnout
* df_poll_state
* df_unemp_state
* df_crime [replaced with fbi crime, due to lack of 2020 data]

```{r merge}

### Merge dataframes
df_merge <- base_redist_df %>% 
  left_join(df_housevote, by = join_by("year" == "year", "state_abv" == "state_po")) %>% 
  left_join(df_turnout %>% select(-state), by = join_by("year" == "year", "state_abv" == "state_abv")) %>% 
  left_join(df_poll_state, by = join_by("year" == "election_year", "state_abv" == "state")) %>% 
  left_join(df_unemp_state, by = join_by("year" == "year", "state_abv" == "state_abv")) %>% 
  left_join(df_fbi_crime, by = join_by("year" == "year", "state_name" == "state")) %>% 
  left_join(df_gdp, by = join_by("year" == "year", "fips" == "GeoFIPS")) %>% 
  left_join(df_wealth_inequality, by = join_by("year" == "year", "state_name" == "state")) %>% 
  left_join(df_stateparty, by = join_by("year" == "year", "state_name" == "state"))

```

```{r additional edits}

### Add population density
df_final.temp1 <- df_merge %>% 
  mutate(vep_density = vep / area,
         vap_density = vap / area)

### Creating Binary Treatment Variables
# Court action status in 2012 (Treatment variable)
treatedVAR.2012.temp <- df_final.temp1 %>%
  mutate(year_num = as.numeric(year)) %>%
  filter(year_num == 2012) %>%
  select(state_abv, redistrict_VAR, court_action_none_count, court_map_drawn_count, court_return_leg_count, court_challenge_rejected_count) %>%
  rename_all(~paste0(., "_VAR")) %>%
  mutate(judiciary_VAR = case_when(redistrict_VAR_VAR == 1
                                   & (court_map_drawn_count_VAR == 1
                                       | court_return_leg_count_VAR == 1
                                       | court_challenge_rejected_count_VAR == 1) ~ 1,
                                   TRUE ~ 0),
         judiciary_unfair_map_VAR = case_when(redistrict_VAR_VAR == 1
                                              & (court_map_drawn_count_VAR == 1
                                                 | court_return_leg_count_VAR == 1) ~ 1,
                                              TRUE ~ 0),
         judiciary_fair_map_VAR = case_when(redistrict_VAR_VAR == 1
                                              & court_challenge_rejected_count_VAR == 1 ~ 1,
                                              TRUE ~ 0)
         )

# Left join court action status to all years 
df_final.temp2 <- df_final.temp1 %>% 
  mutate(year_num = as.numeric(year)) %>% 
  left_join(treatedVAR.2012.temp, by = join_by("state_abv" == "state_abv_VAR"),
             multiple = "all")

```

```{r apply labels}

### Labelled data frame creation
# List of variable names
legend <- df_final.temp2 %>% 
  colnames() %>% 
  as.data.frame()

### Assigning labels
df_final.temp3 <- df_final.temp2 %>% 
  expss::apply_labels(year = "Election Cycle",
               state_name = "State Name",
               state_abv = "State Abbreviation",
               fips = "State's Federal Information Processing System (FIPS) code",
               region = "State's census bureau region",
               division = "State's census bureau division",
               area = "Area in square miles",
               lat = "Center latitudinal coordinate",
               long = "Center longitudinal coordinate",
               redistrict_VAR = "Binary variable of did redistricting occur in this election cycle?",
               court_action_none_count = "No. of redistricting actions in an election cycle without court action/involvement",
               court_map_drawn_count = "No. of redistricting actions in an election cycle, where the court drew the final map",
               court_return_leg_count = "No. of redistricting actions in an election cycle, where the court asked the legislature to redraw the map",
               court_challenge_rejected_count = "No. of redistricting actions in an election cycle, where the court rejected the challenge (map was fair)",
               avg_DEMvote_perc = "Average % of votes cast to DEM candiates across counties",
               avg_REPvote_perc = "Average % of votes cast to REP candiates across counties",
               avg_OTHERvote_perc = "Average % of votes cast to non-DEM/REP candiates across counties",
               state_totalvotes = "Total votes cast in a state",
               vep_turnout_rate = "Voting Eligible Population (VEP) turnout rate",
               vap_turnout_rate = "Voting Able Population (VAP) turnout rate",
               vep = "Voting Eligible Population (VEP)",
               vap = "Voting Able Population (VAP)",
               lagged_vep = "Lagged Voting Eligible Population (VEP) turnout rate",
               vote_closeness = "Ex post voting gap using the partisan differences of average % of votes cast across counties",
               lagged_vote_closeness = "Lagged voting gap using the partisan differences of average % of votes cast across counties",
               violent_crime = "No. of violent crimes reported in a state",
               polling_station = "Number of polling stations per state [Note: exists from 2012 - 2020 only]",
               state_laborForce = "No. of people in state's laborforce",
               state_employed = "No. of employed people in the state",
               state_unemployed = "No. of employed people in the state",
               state_unemploymentRate = "State's unemployment rate",
               gdp_state = "State's real GDP",
               wealth_gini = "State-level GINI coefficient (measure of income inequality)",
               income_mean = "State-level average total household income",
               stateparty_control = "Partisan control over state's legislature (controlling both state house and senate)",
               vep_density = "Population density based on voting eligible population",
               vap_density = "Population density based on voting able population",
               year_num = "Election Cycle (numeric version)",
               redistrict_VAR_VAR = "Merge check variable [ignore please]",
               court_action_none_count_VAR = "Binary variable of was there a redistricting action during the 2012 election cycle, without court action/involvement?",
               court_map_drawn_count_VAR = "Binary variable of was there a redistricting action during the 2012 election cycle, where the courts drew the final map?",
               court_return_leg_count_VAR = "Binary variable of was there a redistricting action during the 2012 election cycle, where the court asked the legislature to redraw the map?",
               court_challenge_rejected_count_VAR = "Binary variable of was there a redistricting action during the 2012 election cycle, where the court rejected the challenge (map was fair)",
               judiciary_VAR = "Binary variable of was there redistricting action during the 2012 election cycle, with ANY court action/involvement?",
               judiciary_unfair_map_VAR = "Binary variable of was there redistricting action during the 2012 election cycle, with court action/involvement that found the map was unfair (needed to be redrawn)?",
               judiciary_fair_map_VAR = "Binary variable of was there redistricting action during the 2012 election cycle, with court action/involvement that found the map was fair (unchanged map)?"
               )


### Assign to df_final
df_final <- df_final.temp3

legend <- sjlabelled::get_label(df_final) %>%
  as.data.frame() %>% 
  rownames_to_column(var = "variable") %>% 
  rename("label" = ".")


```

```{r export}
### Save dataset
# write.csv(df_final, file = paste0("04. Outputs/", today(), "_electiondataset.csv"))
saveRDS(df_final, file = paste0("04. Outputs/", today(), "_electiondataset.rds"))

```

# Additional Data Edits
```{r additional edits}
rm(list=ls())

df <- read_rds("04. Outputs/2024-10-09_electiondataset.rds")

```

