---
title: "U.S. Election Project"
author: "Arthur, Moritz, San Hong"
date: "2024-09-10"
output: html_document
---

# Setup
```{r setup}

# basic R packages
library(here)
library(tidyverse)
library(readr)
library(dplyr)

# ggplot packages
library(ggplot2)
library(RColorBrewer)
library(ggthemes)
library(hrbrthemes)
library(viridis)
library(showtext)
library(ggpmisc)
sysfonts::font_add_google("Roboto Condensed")
showtext_auto()

# geospatial packages
library(maps)
library(usmap)

# regression / coefplot packages
library(plm)
library(broom)
library(dotwhisker)

### Change directory here. 
### As long as file structure is same as github structure, directory does not need to be changed.
knitr::opts_knit$set(root.dir = here::here())

```


```{r import data}
rm(list=ls())

### Import election dataset
df <- read_rds("04. Outputs/2024-10-09_electiondataset.rds")

legend <- df %>% 
  colnames() %>% 
  as.data.frame()

### Import factiva search data
IMPORT.factiva <- read.csv("04. Outputs/FactivaGerrymandering.csv", header = FALSE, stringsAsFactors = FALSE)

df_factiva <- IMPORT.factiva %>%
  filter(grepl("Start Date", V1)) %>%
  mutate(Year = as.numeric(gsub(".*(\\d{4}).*", "\\1", V1)),  # Extract the start year
         Document_Count = as.numeric(V2)) %>% # Convert document count to numeric %>% 
  filter(!is.na(Year), !is.na(Document_Count)) # Remove rows with missing data (if any)

### Import regression p dataframe
p.df <- read_rds("04. Outputs/2024-10-13_regressionDF.rds")
  
```

# Formatting Presets
```{r custom presets & function}

format <- theme_ipsum_rc(base_size = 30)+
      theme(plot.title = element_text(size = 50, lineheight = 0.55),
        plot.subtitle = element_text(size = 30, color = "#939198"),
        axis.title.x = element_text(size = 30, hjust = 0.5),
        axis.title.y = element_text(size = 30, hjust = 0.5),
        axis.text = element_text(lineheight = 0.55),
        legend.position = "none",
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        plot.caption = element_text(size = 30, hjust=0)
        # axis.text.x = element_blank(),
        # panel.background = element_blank()
        )

format2 <- theme_ipsum_rc(base_size = 30)+
      theme(plot.title = element_text(size = 50, lineheight = 0.55, hjust = 0.5),
        plot.subtitle = element_text(size = 30, color = "#939198", hjust = 0.5),
        axis.title.x = element_text(size = 30, hjust = 0.5),
        axis.title.y = element_text(size = 30, hjust = 0.5),
        axis.text = element_text(lineheight = 0.55),
        plot.caption = element_text(size = 30, hjust=0),
        legend.title = element_blank()
        )

f.ggsave <- function(name = "asdf", width.sav = 16, height.sav = 9, dpi.sav = 150, output.type = "png"){
  filepath <- paste0("05. Visualizations/", name, "_", today(), ".", output.type)
  ggsave(filepath, width = width.sav, height = height.sav, units = "in", dpi = dpi.sav)
  # print(filepath)
}

f.tidy.reg <- function(dv.sav = dv, iv.sav = iv, ctrl.sav = ctrl,
                        dataframe.sav = p.df, 
                        effect.sav = "twoways",
                        model.sav = "within"){
  formula_str <- paste0(dv.sav, "~", iv.sav, "+", ctrl.sav)
  out <- plm(as.formula(paste(formula_str, collapse = " ")),
             data = dataframe.sav, effect = effect.sav, model = model.sav)
  tidyout.coef <- tidy(out, conf.int = TRUE, conf.level = 0.9)
  tidyout.fitted <- fitted(out)
  tidyout.resid <- resid(out)
  tidyout <- list(tidyout.coef, tidyout.fitted, tidyout.resid)
  return(tidyout)
}

```


# Visualization Section

## Factiva Search
```{r factiva viz}

# Create the bar chart with the YlOrRd color palette
df_factiva %>% 
  ggplot(aes(x = Year, y = Document_Count)) +
  geom_bar(stat = "identity", fill = brewer.pal(9, "YlOrRd")[5]) +  # Use a specific shade from YlOrRd
  labs(title = "Trend in Articles Mentioning 'Gerrymandering'", 
       x = "\nYear", 
       y = "Number of Articles\n",
       subtitle = "Source: Factiva search") +
  scale_y_continuous(labels = scales::comma_format()) +
  format

# Save visualization
f.ggsave(name = "FactivaViz",
         width.sav = 12,
         height.sav = 8,
         output.type = "jpg")

```
## Geospatial
```{r geospatial viz}

### Preparing data
# Filter data for 2012 and ensure state_abv is character type
df_2012 <- df %>%
  filter(year == 2012) %>%
  mutate(state_abv = as.character(state_abv)) %>%
  select(state_abv, court_action_none_count_VAR, 
         court_map_drawn_count_VAR, court_return_leg_count_VAR, 
         court_challenge_rejected_count_VAR)

# Create a new column that categorizes states based on court action
df_2012 <- df_2012 %>%
  mutate(court_combined_VAR = case_when(
    court_challenge_rejected_count_VAR > 0 ~ "Court finding: Constitutional map  ",
    court_return_leg_count_VAR > 0 ~ "Court finding: Unconstitutional map  ",
    court_map_drawn_count_VAR > 0 ~ "Court finding: Unconstitutional map  ",
    court_action_none_count_VAR > 0 ~ "Redistricting with no court involvement  ",
    TRUE ~ "No redistricting  "
  )) %>% 
  mutate(court_combined_VAR = factor(court_combined_VAR, 
                                     levels = c("No redistricting  ", 
                                               "Redistricting with no court involvement  ",
                                               "Court finding: Constitutional map  ",
                                               "Court finding: Unconstitutional map  "
                                               )))


# Map state abbreviations to full state names for usmap
state_abbreviations <- data.frame(
  state_abv = c(state.abb, "DC"),
  state = c(state.name, "District of Columbia")
)

# Join the full state names to the data
df_2012 <- df_2012 %>%
  left_join(state_abbreviations, by = "state_abv")


### Define a color palette using RColorBrewer (YlOrRd)
color_palette <- brewer.pal(n = 5, name = "YlOrRd")
category_colors <- c("Court finding: Unconstitutional map  " = color_palette[5],  # Deep Red
                     # "Returned to Legislature" = color_palette[4],  # Orange-Red
                     "Court finding: Constitutional map  " = color_palette[3],  # Orange
                     "Redistricting with no court involvement  " = color_palette[2],  # Light Orange-Yellow
                     "No redistricting  " = "white")  # White for None

category_colors <- c("Court finding: Unconstitutional map  " = "#FF687F",
                     "Court finding: Constitutional map  " = "#005E8A",
                     "Redistricting with no court involvement  " = "#FFB188",
                     "No redistricting  " = "#D3D4D6")

### Plot using usmap (now with full state names)
plot_usmap(data = df_2012, values = "court_combined_VAR", regions = "states", color =) +
  scale_fill_manual(values = category_colors, name = "Type of Court Action") +
  labs(title = "\nTypes of Court Involvement in State Redistricting \nDuring the 2012 Election Cycle",
       subtitle = "\n" ) +
  theme(legend.position = "top",  # Move the legend to the bottom
        plot.title = element_text(hjust = 0.5, size = 50, family = "Roboto Condensed", face = "bold", lineheight = 0.55),  # Center the title
        # legend.title = element_text(size = 12, family = "Roboto Condensed", face = "bold"),
        legend.title = element_blank(),
        legend.text = element_text(size = 20, family = "Roboto Condensed"),
        legend.key.size = unit(0.5, "cm"))
  # guides(fill = guide_legend(
  #   title.position = "top",  # Place the legend title above the categories
  #   title.hjust = 0.5,  # Center the legend title
  #   nrow = 1  # Place categories in a single row
  # ))

# Save visualization
f.ggsave(name = "MapViz", width.sav = 12, height.sav = 8, 
         output.type = "jpg")

```

## Regression (Coefficient Plot)
```{r prep regression coefficient}

### Setting variables
dv <- "log(vep_turnout_rate)"
ctrl <- "log(vep_density) + log(state_unemploymentRate) + stateparty_control + log(lagged_vep) + log(vote_closeness)"

### Creating Tidy Data
tidyout_NONE <- f.tidy.reg(dv.sav = dv, iv.sav = "interaction_court_action_none_count", ctrl.sav = ctrl)[[1]] %>% 
  mutate(model_desc = "No court involvement",
         model = "Model A")

tidyout_ANY <- f.tidy.reg(dv.sav = dv, iv.sav = "interaction_judiciary", ctrl.sav = ctrl)[[1]] %>% 
  mutate(model_desc = "ANY court involvement",
         model = "Model B")

tidyout_UNFAIR <- f.tidy.reg(dv.sav = dv, iv.sav = "interaction_judiciary_unfair", ctrl.sav = ctrl)[[1]] %>% 
  mutate(model_desc = "Court finding: Unconstitutional map",
         model = "Model C")

tidyout_FAIR <- f.tidy.reg(dv.sav = dv, iv.sav = "interaction_judiciary_fair", ctrl.sav = ctrl)[[1]] %>% 
  mutate(model_desc = "Court finding: Constitutional map",
         model = "Model D")

### Join tidy data
all_models <- bind_rows(tidyout_NONE, tidyout_ANY, tidyout_UNFAIR, tidyout_FAIR) %>% 
  mutate(model = factor(model, levels = c("Model A", "Model B", "Model C", "Model D")))

### Creating residual data
resid_NONE <- f.tidy.reg(dv.sav = dv, iv.sav = "interaction_court_action_none_count", ctrl.sav = ctrl)[[3]] %>% 
  as.data.frame() %>% 
  mutate(model_desc = "No court involvement",
         model = "Model A")

resid_ANY <- f.tidy.reg(dv.sav = dv, iv.sav = "interaction_judiciary", ctrl.sav = ctrl)[[3]] %>%
  as.data.frame() %>% 
  mutate(model_desc = "ANY court involvement",
         model = "Model B")

resid_UNFAIR <- f.tidy.reg(dv.sav = dv, iv.sav = "interaction_judiciary_unfair", ctrl.sav = ctrl)[[3]] %>%
  as.data.frame() %>% 
  mutate(model_desc = "Court finding: Unconstitutional map",
         model = "Model C")

resid_FAIR <- f.tidy.reg(dv.sav = dv, iv.sav = "interaction_judiciary_fair", ctrl.sav = ctrl)[[3]] %>%
  as.data.frame() %>% 
  mutate(model_desc = "Court finding: Constitutional map",
         model = "Model D")

### Join tidy data
all_resid <- bind_rows(resid_NONE, resid_ANY, resid_UNFAIR, resid_FAIR) %>% 
  mutate(model = factor(model, levels = c("Model A", "Model B", "Model C", "Model D"))) %>% 
  rename(resid = ".")

```

```{r coeff viz}

################################################################################
### Creating Coefficient Plot (Interaction ONLY)

all_models %>% 
  filter(grepl("interaction", term)) %>%
  dwplot(model_order = c("Model A", "Model B", "Model C", "Model D"),
         ci = 0.90,
         dot_args = list(size = 3),
         whisker_args = list(size = 1.5)
         ) %>% 
  relabel_predictors(c(`interaction_court_action_none_count` = "Interaction Term (Treatment x Time):\nNo court involvement ",
                       `interaction_judiciary` = "Interaction Term (Treatment x Time):\nANY court involvement ",
                       `interaction_judiciary_unfair` = "Interaction Term (Treatment x Time):\nCourt finding - Unconstitutional map ",
                       `interaction_judiciary_fair` = "Interaction Term (Treatment x Time):\nCourt finding - Constitutional map "
                       ))+
  geom_vline(xintercept = 0,
               colour = "grey60",
               linetype = 2) +
  labs(title = "Effects on Logged Voter Turnout Rates By \nJudicial Involvements in Redistricting (90% CI)",
       subtitle = "Results from multivariate regression models using time and state fixed effects",
       x = "\nCoefficient Estimates"
       ) +
  format2+
  theme(legend.key.size = unit(2, "cm"),
        panel.border = element_rect(colour = "black", fill=NA))

# Save visualization
f.ggsave(name = "CoeffViz_Interaction",
         width.sav = 16,
         height.sav = 12,
         output.type = "jpg")


################################################################################
### Creating Coefficient Plot (some covariates)

all_models %>% 
  filter(!term %in% c("log(vep_density)", "log(state_unemploymentRate)", "log(lagged_vep)")) %>%
  dwplot(model_order = c("Model A", "Model B", "Model C", "Model D"),
         ci = 0.90,
         dot_args = list(size = 3),
         whisker_args = list(size = 1.5)
         ) %>% 
  relabel_predictors(c(`interaction_court_action_none_count` = "Interaction Term (Treatment x Time):\nNo court involvement ",
                       `interaction_judiciary` = "Interaction Term (Treatment x Time):\nANY court involvement ",
                       `interaction_judiciary_unfair` = "Interaction Term (Treatment x Time):\nCourt finding - Unconstitutional map ",
                       `interaction_judiciary_fair` = "Interaction Term (Treatment x Time):\nCourt finding - Constitutional map ",
                       `stateparty_controlDEM` = "State Legislature Control:\nDemocrats",
                       `stateparty_controlREP` = "State Legislature Control:\nRepublicans",
                       `log(vote_closeness)` = "Closeness of Votes Between Candidates\n(Logged percentage)"
                       ))+
  geom_vline(xintercept = 0,
               colour = "grey60",
               linetype = 2) +
  labs(title = "Effects on Logged Voter Turnout Rates By \nJudicial Involvements in Redistricting (90% CI)",
       subtitle = "Results from multivariate regression models using time and state fixed effects",
       x = "\nCoefficient Estimates"
       ) +
  format2+
  theme(legend.key.size = unit(2, "cm"),
        panel.border = element_rect(colour = "black", fill=NA))

# Save visualization
f.ggsave(name = "CoeffViz_partial",
         width.sav = 16,
         height.sav = 12,
         output.type = "jpg")


################################################################################
### Creating Coefficient Plot (ALL variables)

all_models %>% 
  # filter(term %in% c("log(vep_density)", "")) %>%
  dwplot(model_order = c("Model A", "Model B", "Model C", "Model D"),
         ci = 0.90,
         dot_args = list(size = 3),
         whisker_args = list(size = 1.5)
         ) %>% 
  relabel_predictors(c(`interaction_court_action_none_count` = "Interaction Term (Treatment x Time):\nNo court involvement ",
                       `interaction_judiciary` = "Interaction Term (Treatment x Time):\nANY court involvement ",
                       `interaction_judiciary_unfair` = "Interaction Term (Treatment x Time):\nCourt finding - Unconstitutional map ",
                       `interaction_judiciary_fair` = "Interaction Term (Treatment x Time):\nCourt finding - Constitutional map "
                       ))+
  geom_vline(xintercept = 0,
               colour = "grey60",
               linetype = 2) +
  labs(title = "Effects on Logged Voter Turnout Rates By \nJudicial Involvements in Redistricting (90% CI)",
       subtitle = "Results from multivariate regression models using time and state fixed effects",
       x = "\nCoefficient Estimates"
       ) +
  format2+
  theme(legend.key.size = unit(2, "cm"),
        panel.border = element_rect(colour = "black", fill=NA))

# Save visualization
f.ggsave(name = "CoeffViz_All",
         width.sav = 16,
         height.sav = 12,
         output.type = "jpg")


```



# Misc
```{r}
# Replace NA values in redistrict_count with 0 and clean
X2024_09_24_electiondataset$redistrict_count[is.na(X2024_09_24_electiondataset$redistrict_count)] <- 0
cleaned_data <- X2024_09_24_electiondataset %>%
  filter(!is.na(redistrict_count) & !is.na(vep_turnout_rate))

### Scatter plot of vep_turnout_rate and redistricting counts
ggplot(cleaned_data, aes(x = redistrict_count, y = vep_turnout_rate)) +
  geom_point(alpha = 0.6, color = "blue") +
  labs(title = "VEP Turnout Rate vs. Redistrict Count", 
       x = "Redistrict Count", 
       y = "VEP Turnout Rate") +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  theme_minimal()

### Boxplot visualizing VEP turnout rate grouped by the number of times a county was redistricted
ggplot(cleaned_data, aes(x = as.factor(redistrict_count), y = vep_turnout_rate)) +
  geom_boxplot(fill = "lightgreen") +
  labs(title = "VEP Turnout Rate by Redistrict Count", 
       x = "Redistrict Count", 
       y = "VEP Turnout Rate") +
  theme_minimal()

# Filtering the data for the selected states and removing rows with missing values
cleaned_data_selected_states <- X2024_09_24_electiondataset %>%
  filter(state %in% c("North Carolina", "Wisconsin", "Pennsylvania", "Ohio") & 
           !is.na(redistrict_count) & !is.na(vep_turnout_rate))

### Scatter plot of vep_turnout_rate and redistricting counts
ggplot(cleaned_data_selected_states, aes(x = redistrict_count, y = vep_turnout_rate)) +
  geom_point(alpha = 0.6, color = "blue") +
  labs(title = "VEP Turnout Rate vs. Redistrict Count", 
       x = "Redistrict Count", 
       y = "VEP Turnout Rate") +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  theme_minimal()

### Boxplot visualizing VEP turnout rate grouped by the number of times a county was redistricted
ggplot(cleaned_data_selected_states, aes(x = as.factor(redistrict_count), y = vep_turnout_rate)) +
  geom_boxplot(fill = "lightgreen") +
  labs(title = "VEP Turnout Rate by Redistrict Count", 
       x = "Redistrict Count", 
       y = "VEP Turnout Rate") +
  theme_minimal()

### Residual tests
ggplot(data = all_resid, aes(sample = resid)) +
  geom_qq() +
  stat_qq_line(col="red") +
  facet_wrap(vars(model)) +
  labs(title = "Q-Q Plots: Normality of Residuals for Each Model") +
  theme_minimal()

res_test <- all_resid %>% 
  group_by(model) %>% 
  summarize(tidy(Box.test(resid, lag = 40, type = c("Box-Pierce", "Ljung-Box"))))


### Distribution of DV
cleaned_data <- p.df %>%
  filter(!is.na(vep_turnout_rate))

ggplot(cleaned_data, aes(vep_turnout_rate)) +
  geom_histogram()

hist(p.df$vep_turnout_rate, breaks = 30, col = "#FF687F", border = "white",
     main = "Histogram of Turnout Rates",
     xlab = "VEP Turnout Rate")
  
```

