---
title: "U.S. Election Project"
author: "Arthur, Moritz, San Hong"
date: "2024-09-10"
output: html_document
---

# Setup
```{r setup}

# install.packages("here")
# install.packages("tidyverse")
# install.packages("plm")
# install.packages("stargazer")
# install.packages("readxl")
# install.packages("labelled")
# install.packages("sjlabelled")

library(here)
library(tidyverse)
library(plm)
library(stargazer)
library(readxl)
library(labelled)
library(sjlabelled)
library(broom)
library(GGally)

### Change directory here. 
### As long as file structure is same as github structure, directory does not need to be changed.
knitr::opts_knit$set(root.dir = here::here())

```


```{r import data}

### Clean environment
rm(list=ls())

### Import data created in dataset-creation.rmd
df <- read_rds("04. Outputs/2024-10-24_electiondataset.rds")

### Legend of variables (variable name x explanation of each variable)
legend_df <- sjlabelled::get_label(df) %>%
  as.data.frame() %>% 
  rownames_to_column(var = "variable") %>% 
  rename("label" = ".")

### Data without labels (if necessary)
df_nolabel <- labelled::remove_labels(df)

```


```{r data-check}

temp.variable_list <- c("court_action_none_count_VAR", "court_map_drawn_count_VAR", "court_return_leg_count_VAR", "court_challenge_rejected_count_VAR", "judiciary_VAR", "judiciary_unfair_map_VAR", "judiciary_fair_map_VAR")
temp.year_expression_list <- list(expr(year_num == 2012), expr(year_num >= 2012), expr(TRUE))

for(year.sel in temp.year_expression_list){
    print(as_label(year.sel))
    
    for(val in temp.variable_list){
    
    df %>% 
      filter(!!year.sel) %>%
      select(paste0(val)) %>% 
      table() %>% 
      print()
    
  }
}

### Cleanwork space
rm(list = grep("temp", ls(), value = TRUE))

```


# Functions
```{r custom reg function}
### Creating a function to run multiple regressions simultaneously
f.reg.multi <- function(dv.sav = dv, 
                        iv.sav = iv, 
                        dataframe.sav = p.df, 
                        title.sav = "testingasdf", 
                        effect.sav = "time",
                        type.sav = "within", 
                        dv_label.sav = NULL, 
                        cov_label.sav = NULL,
                        index.sav = NULL,
                        star.type = ifelse(knitr::is_latex_output(),"latex", "text"),
                        star.out = NULL) {
  templist <- list()
  
  for (i in 1:length(dv.sav)){
  
    val <- dv.sav[[i]]
    
    formula_str <- paste0(val, "~", iv.sav)
    
    templist[[i]] <- plm(as.formula(paste(formula_str, collapse = " ")),
                        data = dataframe.sav
                        , effect = effect.sav,
                        model = type.sav
                        , index = index.sav
                        )
  }
    
  stargazer(templist,
          type = star.type,
          out = star.out,
          report = "vc*sp",
          title = "asdf",
          dep.var.labels = paste0(title.sav),
          dep.var.labels.include = T,
          # column.sep.width = "0pt",
          float = FALSE,
          header = FALSE,
          # no.space = TRUE,
          font.size = "small",
          column.labels = dv_label.sav,
          covariate.labels = cov_label.sav
          ) %>%
    return()
  
}

f.reg.multi.iv <- function(dv.sav = dv, 
                        iv.sav = iv, 
                        ctrl.sav = ctrl,
                        dataframe.sav = p.df, 
                        title.sav = "testingasdf", 
                        effect.sav = "time",
                        type.sav = "within", 
                        dv_label.sav = NULL, 
                        cov_label.sav = NULL,
                        index.sav = NULL,
                        star.type = ifelse(knitr::is_latex_output(),"latex", "text"),
                        star.out = NULL,
                        out.sav = boolean()) {
  templist <- list()
  
  for (i in 1:length(iv.sav)){
  
    val <- iv.sav[[i]]
    
    formula_str <- paste0(dv.sav, "~", val, "+", ctrl.sav)
    
    templist[[i]] <- plm(as.formula(paste(formula_str, collapse = " ")),
                        data = dataframe.sav
                        , effect = effect.sav,
                        model = type.sav
                        , index = index.sav
                        )
  } 
  
  if (out.sav == T) {
    return(templist)
  }
    
  stargazer(templist,
          type = star.type,
          out = star.out,
          report = "vc*sp",
          title = "asdf",
          dep.var.labels = paste0(title.sav),
          dep.var.labels.include = T,
          column.sep.width = "0pt",
          float = FALSE,
          header = FALSE,
          no.space = TRUE,
          font.size = "small",
          column.labels = dv_label.sav,
          covariate.labels = cov_label.sav,
          model.numbers = F
          ) %>%
    return()
  
}

```


# Analysis Section
```{r did}

### Panel Data Frame for DID
p.df <- df %>% 
  filter(avg_DEMvote_perc > 0.0001 & avg_REPvote_perc > 0.0001) %>% 
  mutate(time = case_when(year %in% c("2000", "2004", "2008") ~ 0,
                          year %in% c("2012", "2016", "2020") ~ 1)) %>% 
  mutate(stateparty_control = fct_relevel(stateparty_control, "SPLIT", "DEM", "REP")) %>% 
  mutate(interaction_judiciary = time * judiciary_VAR,
         interaction_court_action_none_count = time * court_action_none_count_VAR,
         interaction_court_map_drawn_count = time * court_map_drawn_count_VAR,
         interaction_court_return_leg_count = time * court_return_leg_count_VAR,
         interaction_court_challenge_rejected_count = time * court_challenge_rejected_count_VAR,
         interaction_judiciary_unfair = time * judiciary_unfair_map_VAR,
         interaction_judiciary_fair = time * judiciary_fair_map_VAR,
         interaction_redistrict = time * redistrict_VAR_VAR
         ) %>% 
  pdata.frame(index = c("state_abv", "year")) 

### Legend of variables (variable name x explanation of each variable)
legend_p.df <- sjlabelled::get_label(p.df) %>%
  as.data.frame() %>% 
  rownames_to_column(var = "variable") %>% 
  rename("label" = ".")

# Data-check for DID
table(p.df$time)
table(p.df$judiciary_VAR)
table(p.df$judiciary_VAR[p.df$time == 1])
table(p.df$judiciary_VAR[p.df$time == 0])
table(p.df$interaction_judiciary)


```

```{r export}
### Save dataset
saveRDS(p.df, file = paste0("04. Outputs/", today(), "_regressionDF.rds"))

p.df <- read_rds("04. Outputs/2024-10-13_regressionDF.rds")

```

```{r multi IV testing}
dv <- "log(vep_turnout_rate)"
iv <- c("interaction_court_action_none_count", "interaction_judiciary",  "interaction_judiciary_unfair", "interaction_judiciary_fair")
ctrl <- "log(vep_density) + log(state_unemploymentRate) + stateparty_control + log(lagged_vep) + log(vote_closeness)"

dv_label <- c("Model A", "Model B", "Model C", "Model D")

cov_label <- c("Interaction (NO Court Involvement X Time)",
               "Interaction (ANY Court Involvement X Time)",
               "Interaction (Court Finding: UNCONSTITUTIONAL Map X Time)",
               "Interaction (Court Finding: CONSTITUTIONAL Map X Time)",
               "Voter Population Density (Logged)",
               "State Unemployment Rate  (Logged)",
               "State legislature control - DEM",
               "State legislature control - REP",
               "Vote Closeness of Candidates (Logged)",
               "Prev. General Election VEP Turnout Rate (Logged)"
               )

f.reg.multi.iv(dv.sav = dv, 
               iv.sav = iv, 
               ctrl.sav = ctrl,
               dataframe.sav = p.df, 
               title.sav = "Voting Eligible Population (VEP) Turnout Rate (Logged)", 
               effect.sav = "twoways",
               type.sav = "within", 
               dv_label.sav = dv_label, cov_label.sav = cov_label,
               star.type = "html",
               star.out = paste0("05. Visualizations/", today(), "-regression-tbl-did.html"),
               out.sav = F)

```

# Robust Standard Error
```{r}

robustSE_check <- plm(log(vep_turnout_rate) ~ interaction_judiciary_fair + log(vep_density) + log(state_unemploymentRate) + stateparty_control + log(lagged_vep) + log(vote_closeness),
                      data = p.df, effect = "twoways", model = "within")

robustSE_check %>% 
  summary(robust = T)

```

# Effects of Just Redistricting
```{r}

dv <- "log(vep_turnout_rate)"
iv <- c("interaction_redistrict")
ctrl <- "log(vep_density) + log(state_unemploymentRate) + stateparty_control + log(lagged_vep) + log(vote_closeness)"

f.reg.multi.iv(dv.sav = dv, 
               iv.sav = iv, 
               ctrl.sav = ctrl,
               dataframe.sav = p.df, 
               title.sav = "Voting Eligible Population (VEP) Turnout Rate (Logged)", 
               effect.sav = "twoways",
               type.sav = "within", 
               # dv_label.sav = dv_label, cov_label.sav = cov_label,
               # star.type = "html",
               # star.out = paste0("05. Visualizations/", today(), "-regression-tbl-did.html"),
               # star.type = "latex",
               # star.out = paste0("05. Visualizations/", today(), "-regression-tbl-did.tex"),
               out.sav = F)

```


