---
title: "Reference Code for Rbinding"
output: html_document
date: "2024-09-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
##################################################################################################
#################### DATABASE BUILDING SECTION ###################################################
##################################################################################################

library(XML)
library(xml2)
library(tidyverse)
library(tictoc)

## Import all XML files and Compile all into 1 Data Frame

# Note: Please set your own working directory before running the code

setwd("C:/Users/arthu/Documents/_Arthur/[RA] ACI/04. R Code - Corpus")

xml_list <- list.files(path="Agreement Mod XML", full.names = TRUE, recursive = TRUE )
meta_data <- read.csv("meta_byNewDocID_Jan-09-2024.csv")

# San Hong Version
tic()
meta_data_len <- ncol(meta_data)

df <- data.frame(matrix(ncol = (meta_data_len + 3), nrow = 0))
colnames(df) <- c('name','chapter', 'text', colnames(meta_data[,]))

for (xml_file in xml_list){
  tryCatch({
    # Read the XML file
    xml_data <- read_xml(xml_file, options = "HUGE")
    
    # Extract the text within the <chapter> tags
    chapter_text <- xml_data %>% 
      xml_find_all("//chapter") %>% 
      xml_text()
    
    # Convert the extracted text to a data frame
    data <- data.frame(chapter_text = chapter_text)
  },
  error = function(e) {
    print(paste("Error here:", xml_file))
    print(e$message)
  })
  data <- data %>%
    rowid_to_column(var = "chapter")
  data$name <- basename(xml_file)
  for (i in 1:nrow(meta_data)){
    for (j in 1:nrow(data)){
      if(data$name[1] == meta_data$name[i] & data$chapter[j] == meta_data$chapter[i]){
        data[j,c(4:(meta_data_len+2))] <- meta_data[i,c(2:meta_data_len)]
      }
    }
  }
  df <- rbind(df, data)
}

df <- df[,c(2:ncol(df))]
rm(data, xml_file, xml_list, xml_data,i,j,chapter_text,meta_data_len)

toc()


####################################
### Arthur's hacked SQL Version
library(sqldf)

xml_list <- list.files(path="Agreement Mod XML", full.names = TRUE, recursive = TRUE )
meta_data <- read.csv("meta_byNewDocID_Jan-09-2024.csv")

tic()
df <- data.frame(matrix(ncol = 3, nrow = 0))

for (xml_file in xml_list){
  tryCatch({
    # Read the XML file
    xml_data <- read_xml(xml_file, options = "HUGE")
    
    # Extract the text within the <chapter> tags
    chapter_text <- xml_data %>% 
      xml_find_all("//chapter") %>% 
      xml_text()
    
    # Convert the extracted text to a data frame
    data <- data.frame(chapter_text = chapter_text)
  },
  error = function(e) {
    print(paste("Error here:", xml_file))
    print(e$message)
  })
  # Add the chapter number and the file name
  data <- data %>%
    rowid_to_column(var = "chapter") %>%
    mutate(name = basename(xml_file))
  
  # Append the data to the final dataframe
  df <- rbind(df, data)
}

sql <- sqldf(
  "
  select 
    df.chapter_text,
    md.*
  from df
  left join meta_data md
  on (df.name = md.name
  AND df.chapter = md.chapter)
  "
)
toc()

rm(data, xml_file, xml_list, chapter_text,)

#############################################################
## Write Sample XML from Data Frame for Documentation Purpose

# Create a function to convert a row in the data frame to an XML node
row_to_xml <- function(row) {
  xml_data <- newXMLNode("Agreement")
  addChildren(xml_data,
              newXMLNode("text", as.character(row$chapter_text)),
              lapply(2:ncol(row), function(i) {
                newXMLNode(names(row)[i], as.character(row[i]))
              })
  )
  return(xml_data)
}

# Create the XML document and add rows as nodes
xml_doc <- newXMLDoc()
xml_root <- newXMLNode("Agreements")
addChildren(xml_doc, xml_root)

for (i in 1:nrow(sql)) {
  xml_node <- row_to_xml(sql[i, ])
  addChildren(xml_root, xml_node)
}

# Save the XML document to a file
saveXML(xml_doc, file = "dataFrameSample_withMetaData.xml") # check if output directory is correct

rm(xml_doc, xml_node, xml_root, row_to_xml)

# OPTIONAL: Update Meta Data by Doc ID CSV
df1 <- df[,-c(2)]
write.csv(df1, "Metadata for Agreements/Metadata by DocID/meta_byDocID.csv")


```

